CREATE TABLE SUBSCRIBER(
    SUBSC_ID NUMBER,
    MSISDN VARCHAR2(11) NOT NULL UNIQUE,
    NAME VARCHAR2(100) NOT NULL,
    SURNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(20) NOT NULL,
    SDATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(2) DEFAULT 'A',
);


ALTER TABLE SUBSCRIBER ADD(
    CONSTRAINT subsc_id_pk PRIMARY KEY (SUBSC_ID)
);

CREATE SEQUENCE subsc_id_sequence start with 1 increment by 1;


CREATE TABLE PACKAGE(
    PACKAGE_ID NUMBER,
    PACKAGE_NAME VARCHAR2(200),
    AMOUNT_VOICE NUMBER,
    AMOUNT_DATA NUMBER,
    AMOUNT_SMS NUMBER,
    DURATION NUMBER
);

ALTER TABLE PACKAGE ADD(
    CONSTRAINT package_id_pk PRIMARY KEY (PACKAGE_ID)
);

CREATE SEQUENCE package_id_sequence start with 1 increment by 1;

CREATE TABLE BALANCE(
    SUBSC_ID NUMBER,
    PACKAGE_ID NUMBER,
    BAL_LVL_VOICE NUMBER DEFAULT 0,
    BAL_LVL_SMS NUMBER DEFAULT 0,
    BAL_LVL_DATA NUMBER DEFAULT 0,
    PRICE NUMBER DEFAULT 0,
    SDATE DATE DEFAULT SYSDATE,
    EDATE DATE DEFAULT SYSDATE
);


ALTER TABLE BALANCE ADD(
    CONSTRAINT subsc_id_fk FOREIGN KEY (SUBSC_ID) REFERENCES SUBSCRIBER(SUBSC_ID) ON DELETE CASCADE,
    CONSTRAINT package_id_fk FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID) ON DELETE CASCADE
);


CREATE TABLE USAGE_RECORD (
    USAGE_RECORD_ID NUMBER NOT NULL,
    MSISDN VARCHAR2(11) NOT NULL,
    USAGE_DATE TIMESTAMP,
    VOICE_DURATION NUMBER,
    SMS_COUNT NUMBER,
    DATA_USAGE NUMBER,
    INTERNET_PAGE VARCHAR2(255),
    DESTINATION VARCHAR2(255)
);
ALTER TABLE USAGE_RECORD ADD(
    CONSTRAINT usage_record_id PRIMARY KEY (USAGE_RECORD_ID)
    );
    
CREATE SEQUENCE usage_record_id_sequence start with 1 increment by 1;


